In [2]:
#A1) Program to add two matrices

X = [[1,2,3], [2,3,4], [3,4,5]]
Y = [[9,3,4], [7,3,2], [3,7,6]]

result = [[X[i][j] + Y[i][j] for j in range
          (len (X[0])) for i in range (len(X))]]

for r in result:
    print(r)

[10, 9, 6, 5, 6, 11, 7, 6, 11]


In [4]:
#A2) Multiply two Matrices
import numpy as np

A = [[12,7,3], [4,5,6],[7,8,9]]
B = [[5,8,1],[3,4,5],[5,6,7]]
     
result =[[0,0,0],[0,0,0],[0,0,0]]
    
result = np.dot(A,B)

for r in result:
     print(r)
     

[ 96 142  68]
[65 88 71]
[104 142 110]


In [6]:
#A3) traspose of matric

N = 4
def transpose(A):
    for i in range(N):
        for j in range(i+1, N):
            A[i][j], A[j][i] = A [j][i], A[i][j]
            
A = [[1,1,1,1], [2,2,2,2], [3,3,3,3], [4,4,4,4]]
transpose(A)

print("Matrix is")
for i in range(N):
    for j in range(N):
        print(A[i][j], " ", end='')
    print()

Matrix is
1  2  3  4  
1  2  3  4  
1  2  3  4  
1  2  3  4  


In [12]:
#A4) Sort words in Alphabetic Order
def Func(S):
    W = S.split(" ")
    for i in range(len(W)):
        W[i]=W[i].lower()
        S = sorted(W)
        print(' '.join(S))
    
S = "This is my alphabetic sorting code"
Func(S)

    

alphabetic code is my sorting this
alphabetic code is my sorting this
alphabetic code is my sorting this
alphabetic code is my sorting this
alphabetic code is my sorting this
alphabetic code is my sorting this


In [15]:
#A5) Remove punctuation marks

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
my_str = "Hello!!!, he said  ---and went."

no_punct =""
for char in my_str:
    if char not in punctuations:
        no_punct = no_punct + char 
print(no_punct)

Hello he said  and went
